# Generated by Django 5.1 on 2024-10-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('ano', models.IntegerField(max_length=4)),
                ('genero', models.CharField(max_length=100)),
                ('id_livros', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
